[package]
name = "monopoly"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
async-tungstenite = "0.25.1"
eyre = "0.6.12"
futures = "0.3.30"
tide = "0.16.0"